require: rubocop-rails

AllCops:
    NewCops: enable
    Exclude:
    - "db/**/*"
    - "bin/*" 
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"
    - "app/helpers/**/*"

Style/Documentation:
  Enabled: false