name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      
      - name: Setup Rubocop
        run: |
          gem install rubocop-rails
          rubocop --version
      - name: Rubocop Report
        run: rubocop --color